# Project information
site_name: Accion Labs Delivery Management
site_description: Comprehensive delivery management handbook and resources
site_author: Accion Labs
# site_url: https://mahasri.github.io/accionlabs-delivery-management/

# Repository
repo_name: mahasri/accionlabs-delivery-management
repo_url: https://github.com/mahasri/accionlabs-delivery-management
edit_uri: edit/main/docs/

# Theme Configuration
theme:
  name: material
  language: en
  palette:
    # Light mode only
    - scheme: default
      primary: indigo
      accent: indigo
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.delay
    - navigation.instant.loading
    - navigation.instant.previous
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - navigation.footer
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye
  logo: assets/logo.png
  favicon: assets/favicon.ico

# Navigation Structure
nav:
  - Delivery Handbook:
    - Introduction: introduction/index.md
    - Project Initiation: project-initiation/index.md
    - Transition: transition/index.md
    - Delivery Execution: delivery-execution/index.md
    - Innovation Engineering Services (Architecture & Design): delivery-execution/innovation-engineering-services/index.md
    - SDLC - New Development: delivery-execution/sdlc-new-development/index.md
    - SDLC - Enhancements & Support: delivery-execution/sdlc-enhancements-support/index.md
    - End-End Ownership: delivery-execution/end-end-ownership.md
    - Value-Driven Delivery: value-driven-delivery/index.md
    - GenAI Adoption: genai-adoption/index.md
    - GenAI Statistics Report: genai-adoption/genai-statistics-report.md
    - Agile Methodologies: agile-methodologies/index.md
    - Best Practices:
      - Overview: best-practices/index.md
      - Requirements Gathering: best-practices/requirements-gathering.md
      - Architecture & Design: best-practices/architecture-design.md
      - Development: best-practices/development.md
      - QA Best Practices: best-practices/qa-best-practices.md
      - Testing & QA Process: best-practices/testing-qa-process.md
      - Release Planning: best-practices/release-planning.md
    - Metrics & KPIs: metrics-kpis/index.md
  - Delivery Excellence:
    - '📚 Delivery Handbook': delivery-excellence/delivery-handbook.md
    - Overview: delivery-excellence/index.md
    - Checklist: delivery-excellence/checklist.md
    - Induction: delivery-excellence/induction-process.md
    - Transition: delivery-excellence/transition.md
    - Delivery Execution:
      - Overview: delivery-excellence/delivery-execution/index.md
      - Innovation Engineering Services: delivery-excellence/delivery-execution/innovation-engineering-services/index.md
      - SDLC - New Development: delivery-excellence/delivery-execution/sdlc-new-development/index.md
      - SDLC - Enhancements & Support: delivery-excellence/delivery-execution/sdlc-enhancements-support/index.md
      - End-End Ownership: delivery-execution/end-end-ownership.md
      - Value-Driven Delivery: delivery-excellence/delivery-execution/value-driven-delivery/index.md
      - GenAI Adoption: delivery-excellence/delivery-execution/genai-adoption/index.md
      - '🤖 GenAI Adoption Report': genai-adoption/genai-adoption-report.md
      - Metrics & KPI: delivery-excellence/delivery-execution/metrics-kpi/index.md
    - Delivery Governance:
      - Overview: delivery-excellence/delivery-governance/index.md
      - Daily Ceremonies: delivery-excellence/delivery-cadences/daily-ceremonies.md
      - Bi-weekly / WSR: delivery-excellence/delivery-cadences/bi-weekly-wsr.md
      - MBR: delivery-excellence/delivery-cadences/bi-weekly-mbr.md
      - QBR: delivery-excellence/delivery-cadences/qbr.md
      - Townhall: delivery-excellence/delivery-cadences/ahm-townhall.md
      - Customer Visits: delivery-excellence/delivery-cadences/customer-visits.md
      - Accolades: delivery-excellence/delivery-cadences/rewards-recognitions.md
      - CSAT: delivery-excellence/delivery-cadences/csat.md
    - Program Value Board:
      - Metrics & Methodologies: delivery-excellence/program-value-board/process-metrics.md
      - Review Checklist: delivery-excellence/program-value-board/review-template.md
      - PVB Review Team: delivery-excellence/program-value-board/pvb-review-team.md
      - Review Reports: delivery-excellence/program-value-board/review-reports.md
    - Architecture Value Board:
      - Tools & Technologies: delivery-excellence/architecture-value-board/tools-technologies.md
      - Review Checklist: delivery-excellence/architecture-value-board/review-checklist.md
      - AVB Review Team: delivery-excellence/architecture-value-board/avb-review-team.md
      - Review Reports: delivery-excellence/architecture-value-board/review-reports.md
    - '🎯 Maturity Dashboard': delivery-excellence/maturity-dashboard.md
    - Key Resources: delivery-excellence/key-resources.md



# Plugins
plugins:
  - search:
      lang: en
  - minify:
      minify_html: true

# Extra CSS and JS
extra_css:
  - stylesheets/extra.css

extra_javascript:
  - https://unpkg.com/mermaid@8.13.0/dist/mermaid.min.js
  - javascripts/mermaid-init.js
  - javascripts/collapsible-nav.js



# Theme overrides
# overrides:
#   main.html: overrides/main.html

# Markdown Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - codehilite:
      guess_lang: false
      use_pygments: true
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      title: On this page
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Extra
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/accionlabs
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/company/accionlabs
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/accionlabs
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  generator: false

# Copyright
copyright: Copyright &copy; 2024 Accion Labs

# Validation
validation:
  nav:
    omitted_files: ignore
  not_found: warn
